#' This function automatically calculates the accuracy
#' 
#' This function automatically calculates the accuracy.
#' 
#' @param pre_probs prediction probability from the model 
#' @param labels true labels
#' @param threshold  the threshold to determine the predicted labels,defualt is 0.5
#' @return 
#' \item{accuracy}{accuracy of the model}
#' @author  Chenxi Zhu
#' @seealso 
#' \code{\link{print.my_logistic_regression}},\code{\link{plot_roc}},\code{\link{predict.my_logistic_regression}}
#' @references Nick T G, Campbell K M. Logistic regression[J]. Topics in biostatistics, 2007:273-301.
#' @export
#' @examples
#' 
#' # build a logistic regression model
#' data("test_data")
#' model<-my_logistic_regression(y~x1+x2,data=test_data)
#' pre <- predict(model,test_data)
#' accuracy(pre$prob,test_data$y)
#' 

# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
accuracy <- function(pre_probs, labels, threshold = 0.5) {
    .Call('_GLMhw_accuracy', PACKAGE = 'GLMhw', pre_probs, labels, threshold)
}

